In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matpotlib inline #jupyter

UsageError: Line magic function `%matpotlib` not found.


In [2]:
a = np.arange(100)

In [3]:
a[0], a[2], a[-1]

(0, 2, 99)

In [4]:
a[0:5]

array([0, 1, 2, 3, 4])

In [5]:
a[0:10:2]

array([0, 2, 4, 6, 8])

In [6]:
a[:5]

array([0, 1, 2, 3, 4])

In [7]:
a[::-20]

array([99, 79, 59, 39, 19])

In [8]:
a = np.diag([1, 2, 3])

In [9]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [11]:
a[1, 1]

2

In [12]:
a[2, 1] = 10

In [13]:
a

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0, 10,  3]])

In [14]:
a[:, 2]

array([0, 0, 3])

In [16]:
a[0]

array([1, 0, 0])